
Import('env objects')

def make_test(name):

  test_obj = env.Object(
    '.o/%s' % name,
    'test%s.c' % name
  )

  test = env.Program(
    '%s.test' % name,
    source=objects + [
      test_obj
    ]
  )

  run_test = Command(
    target='#test/results/%s.result' % name,
    source=test,
    action='$SOURCE | tee $TARGET'
  )

  Depends(run_test, test)

  return run_test

tests = [
  make_test('001'),
  make_test('002')
]

AlwaysBuild(tests)

Return('tests')
